### ISSUE TITLE
Output flow result in github action

### ISSUE THREAD

**Issue by kelianClerc** [mobile-dev-inc/action-maestro-cloud#14]
Currently the action only takes inputs, and print result. 

Is it possible to output data about the completed flow in the step output, for it to be used by other steps.
Like:
-  the list of flow that succedded
- the list of flow that failed
- the percentage of flow that failed
- etc

**Comment by Dambakk** [comment]
+1 on this! We would like to get ahold of the generated junit report to be able to pass it on to other tools.

**Comment by orestesgaolin** [comment]
Frankly even text output would be sufficient for us e.g.

```
[Passed] test_1
[Passed] test_2
[Passed] test_3

3/3 Flows Passed
```

**Comment by axelniklasson** [comment]
Hi folks! We currently output the results in text from the action, so just want to check whether that solves your use case?

<img width="510" alt="image" src="https://github.com/mobile-dev-inc/action-maestro-cloud/assets/6113675/c21889ac-f055-4b44-870b-7e059b00994b">

**Comment by axelniklasson** [comment]
Hey folks! If you upgrade to version `1.5.0` you can now access information about the console URL, upload status and each Flow in the output.

```yaml
- uses: mobile-dev-inc/action-maestro-cloud@v1.5.0
  with:
    api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
    app-file: <your_app_file>
    # ... any other parameters

- name: Access Outputs
  if: always()
  run: |
    echo "Console URL: ${{ steps.upload.outputs.MAESTRO_CLOUD_CONSOLE_URL }}"
    echo "Flow Results: ${{ steps.upload.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}"
    echo "Upload Status: ${{ steps.upload.outputs.MAESTRO_CLOUD_UPLOAD_STATUS }}"
```

More info [here](https://github.com/mobile-dev-inc/action-maestro-cloud#accessing-output)!
