### ISSUE TITLE
 Proposal to output console URL

### ISSUE THREAD

**Issue by hkusu** [mobile-dev-inc/action-maestro-cloud#18]
It would be nice if the console URL could be used in subsequent steps.

https://github.com/mobile-dev-inc/action-maestro-cloud/blob/2458fd509d6e632b59927fb17a94eef625fa18bd/index.ts#L100C68-L100C78

```
core.setOutput('console-url', consoleUrl)
```

Useful for writing the URL as a comment in the pull request or outputting it to the [summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

**Comment by axelniklasson** [comment]
Hey @hkusu! If you upgrade to version `1.5.0` you can now access information about the console URL, upload status and each Flow in the output.

```yaml
- uses: mobile-dev-inc/action-maestro-cloud@v1.5.0
  with:
    api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
    app-file: <your_app_file>
    # ... any other parameters

- name: Access Outputs
  if: always()
  run: |
    echo "Console URL: ${{ steps.upload.outputs.MAESTRO_CLOUD_CONSOLE_URL }}"
    echo "Flow Results: ${{ steps.upload.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}"
    echo "Upload Status: ${{ steps.upload.outputs.MAESTRO_CLOUD_UPLOAD_STATUS }}"
```

More info [here](https://github.com/mobile-dev-inc/action-maestro-cloud#accessing-output)!
