### ISSUE TITLE
Action passes even upon test execution failure

### ISSUE THREAD

**Issue by ivohashamov** [mobile-dev-inc/action-maestro-cloud#28]
My team and I have been using Maestro for the past few weeks and have enjoyed the experience a lot! We use the action-maestro-cloud to run our E2E tests daily.

However, we just noticed that the action still passes whenever there's a failure in the test run in the cloud. This is problematic, as we always have to manually check if the tests actually passed, instead of getting notified by GitHub.

Below is a screenshot of the workflow run. As you can see, the first tests failed, canceling the execution of all follow-up tests, but the step and the whole job still passed.

![image](https://github.com/mobile-dev-inc/action-maestro-cloud/assets/63168603/c9c9c991-a461-4876-add5-a8cf6ca3d01f)

We know that the upload and running of our tests work with the current setup, as we already had plenty of runs where everything went through successfully. Any ideas about what might be causing the issue?

Below you can see our job YAML as well.

```yaml
  mobile-test:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Staging App APK
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cd-rn.yml
          workflow_conclusion: success
          name: app-android-staging
          check_artifacts: true
          if_no_artifact_found: fail
          path: modules/e2e

      - name: Upload and Run Maestro Tests
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: modules/e2e/app-staging-release.apk
          workspace: modules/e2e/tests/e2e-mobile

```

**Comment by axelniklasson** [comment]
Update here: won't have time to work on this for the coming future due to changing priorities on our side, but leaving the issue open

**Comment by henninghall** [comment]
Experienced the same issue due to a test timeout. Bugs could easily slip through when everything looks green.  @ivohashamov's workaround worked fine.

**Comment by nicholascm** [comment]
> Experienced the same issue due to a test timeout. Bugs could easily slip through when everything looks green. @ivohashamov's workaround worked fine.

Yes this was happening for us also.

**Comment by loremattei** [comment]
We've experienced the same issue recently. @ivohashamov  thanks for the workaround!

@axelniklasson I obviously don't know about your internal priorities, but I'd say that a test automation system that doesn't report failures reliably is pretty much useless. This looks like a very high priority to me tbh.

**Comment by axelniklasson** [comment]
@loremattei I want to reiterate what I stated above - when an upload is marked as **failed**, the GitHub workflow run will also be marked as **failed**. The reason it is not being done in this case is due to it being _canceled_, which is intentional since it might be due to test timeouts or other issues and we did not want to block people's CI pipelines. 

We do welcome pull requests, so if you (or anyone else following along) are open to raising a PR that adds a new argument called `fail-on-cancellation` that when set to `true` marks the action as failed instead of passed like it works today we'll be happy to help it get merged.

**Comment by loremattei** [comment]
@axelniklasson I'm sorry, I was probably too short in my description above. Let me try to expand and explain the critical issue here. 

What we are experiencing is that: 
- A test fails because it doesn't find an expected element. 
- The upload is marked as timed out, not failed. 
- **Maestro marks the workflow as successful, even if a test is failed**. Note that there are no signs on this in the CI until you open up the log for the relevant step. 

Moreover, this seems to happen _consistently_ when we retry a failed test (if the test failed because of a missing element), i.e.:
- First run: the test fails and it's reported as failed.
- Second run: the test still fails, but the workflow is marked as successful. 

This is what we see in the log:
```
[Passed] TestXXX
[Passed] TestYYY
[Failed] TestZZZ.yml (Element not found: Id matching regex: <something>)
Timed out waiting for Upload to complete. View the Upload in the console for more information
```


So, this is not a matter of adding an optional parameter (and I would argue that I don't agree with the default behaviour anyway: I want my tests to be green only when everything run successfully, not when something got cancelled. As a minimum, I would make this the default and add a parameter to make the workflow pass on cancelled tests), but this seems to be a system wide problem between Maestro-cloud action and Maestro-cloud CI system.

**Comment by axelniklasson** [comment]
@loremattei Roger, thanks for expanding on what you mean - it is clearer now, thanks!

**Comment by adamdanielczyk** [comment]
We are also encountering this issue with `mobile-dev-inc/action-maestro-cloud@v3`.

We rely on blocking Maestro Cloud runs in GitHub Actions for a production mobile application. When an upload is canceled or times out after build or test failures, the action can still complete successfully, leaving both the step and the job green. This makes it difficult to use the action as a reliable CI quality gate because a successful GitHub Actions status does not necessarily mean that the Maestro tests succeeded.

Our current workaround is to inspect `MAESTRO_CLOUD_UPLOAD_STATUS` after the action and fail the job unless its value is exactly `SUCCESS`. We also have to treat a missing status as a failure:

```yaml
- uses: mobile-dev-inc/action-maestro-cloud@v3
  id: maestro
  with:
    # ...
    async: false

- name: Verify Maestro Cloud result
  env:
    MAESTRO_CLOUD_UPLOAD_STATUS: ${{ steps.maestro.outputs.MAESTRO_CLOUD_UPLOAD_STATUS }}
  run: |
    if [[ "$MAESTRO_CLOUD_UPLOAD_STATUS" != "SUCCESS" ]]; then
      echo "Maestro Cloud run did not complete successfully: ${MAESTRO_CLOUD_UPLOAD_STATUS:-missing status}"
      exit 1
    fi
```

It would be very helpful if blocking mode propagated every non-success terminal state to the action exit status, or provided an input such as `fail-on-cancellation`. That would let teams rely on the action directly without duplicating this logic in every workflow.
